<?php

return array(
  array('state' => 'Alabama', 'state_code', 'AL'),
  array('state' => 'Alaska', 'state_code', 'AK'),
  array('state' => 'Arizona', 'state_code', 'AZ'),
  array('state' => 'Arkansas', 'state_code', 'AR'),
  array('state' => 'California', 'state_code', 'CA'),
  array('state' => 'Colorado', 'state_code', 'CO'),
  array('state' => 'Connecticut', 'state_code', 'CT'),
  array('state' => 'Delaware', 'state_code', 'DE'),
  array('state' => 'District of Columbia', 'state_code', 'DC'),
  array('state' => 'Florida', 'state_code', 'FL'),
  array('state' => 'Georgia', 'state_code', 'GA'),
  array('state' => 'Hawaii', 'state_code', 'HI'),
  array('state' => 'Idaho', 'state_code', 'ID'),
  array('state' => 'Illinois', 'state_code', 'IL'),
  array('state' => 'Indiana', 'state_code', 'IN'),
  array('state' => 'Iowa', 'state_code', 'IA'),
  array('state' => 'Kansas', 'state_code', 'KS'),
  array('state' => 'Kentucky', 'state_code', 'KY'),
  array('state' => 'Louisiana', 'state_code', 'LA'),
  array('state' => 'Maine', 'state_code', 'ME'),
  array('state' => 'Maryland', 'state_code', 'MD'),
  array('state' => 'Massachussets', 'state_code', 'MA'),
  array('state' => 'Michigan', 'state_code', 'MI'),
  array('state' => 'Minnesota', 'state_code', 'MN'),
  array('state' => 'Mississipi', 'state_code', 'MS'),
  array('state' => 'Missouri', 'state_code', 'MO'),
  array('state' => 'Montana', 'state_code', 'MT'),
  array('state' => 'Nebraska', 'state_code', 'NE'),
);
